// /mnt/data/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'auth/login_screen.dart';
import 'auth/otp_screen.dart';
import 'auth/signup_screen.dart'; // optional
import 'screens/home/home_screen.dart';
import 'screens/book/book_ride_screen.dart';
import 'screens/offer/offer_ride_screen.dart';
import 'screens/profile/profile_screen.dart';


// If you have firebase_options.dart generated by flutterfire CLI, uncomment:
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // If you have firebase_options.dart, use:
    // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

    // Otherwise, simple initialize (plist/json present for each platform)
    await Firebase.initializeApp();
    print('Firebase initialized');
  } catch (e, st) {
    // log initialization error — the app can still show an error UI if needed
    print('Firebase.initializeApp error: $e\n$st');
    // rethrow if you want app to crash here, but we'll continue so authState can show login screen
  }

  runApp(const RideShareApp());
}

class RideShareApp extends StatelessWidget {
  const RideShareApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
  title: 'RideShare',
  theme: ThemeData(primarySwatch: Colors.deepPurple),
  debugShowCheckedModeBanner: false,
  initialRoute: '/',
  routes: {
    '/': (context) => const Root(),
    // '/login': (context) => const LoginScreen(),
    // '/otp': (context) => const OtpScreen(),
    // '/signup-profile': (context) => const SignupProfileScreen(), // optional
    '/home': (context) => const HomeScreen(),
    '/book': (context) => const BookRideScreen(),
    '/offer': (context) => const OfferRideScreen(),
    '/profile': (context) => const ProfileScreen(),
  },
);


  }
}

class Root extends StatelessWidget {
  const Root({super.key});

  @override
  Widget build(BuildContext context) {
    // StreamBuilder listens to auth changes and rebuilds automatically
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // still initializing auth state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // error while listening
        if (snapshot.hasError) {
          return Scaffold(
            body: Center(child: Text('Auth error: ${snapshot.error}')),
          );
        }

        // user is signed in
        if (snapshot.hasData && snapshot.data != null) {
          return const HomeScreen();
        }

        // user is NOT signed in
        return const HomeScreen();
      },
    );
  }
}
